astra_db:
  collection_name: "ecommercedata"

embedding_model:
    provider: "openai"
    model_name: "text-embedding-3-large"

llm:
    provider: "groq"
    model_name: "deepseek-r1-distill-llama-70b"

retriever:
  top_k: 10
